print("==========================")
print(" MY PRIMER PROGRAMA PYTHON")
print("==========================")
print("Nombre: Lukas")
print("Carrera: Ingenieria de sIstemas ")
print("Semestre: Primero")
print("Estoy aprendiendo Git y Github")
print("Aña chucho Bv")
print("Nombre:Camila")
print("nombre: Leonardo")
print("estoy aprendiendo usar print")
